services:
    # コンテナ名
    jupyterlab:
        build: .
        image: jupyterlab-test-img
        container_name: dev-app
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - "6666:6666"
        command:
            jupyter-lab --ip 0.0.0.0 --allow-root -b localhost