services:
    # コンテナ名
    dev-app:
        build: .
        image: dev-app-img
        container_name: dev-app-container
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - "80:80"
        command: gunicorn main:app --bind 0.0.0.0:80