services:
    # コンテナ名
    dev-app2:
        build: .
        image: dev-app-img2
        container_name: dev-app-container2
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - "80:80"
        command: gunicorn main:app --bind 0.0.0.0:80